ForkbombEu/wallet

- android/.idea/codeStyles/Project.xml
- android/.idea/codeStyles/codeStyleConfig.xml
- android/app/src/main/java/walletamous/ionic/io/MainActivity.java
- android/app/src/main/java/walletamous/ionic/io/OldAndroidVersionException.java
- android/app/src/main/java/walletamous/ionic/io/TEE.java
- ios/App/App.xcodeproj/project.pbxproj
- ios/App/App/TEEPlugin.m
- ios/App/App/TEEPlugin.swift
- pnpm-lock.yaml
- src/lib/keypairoom/Questions.svelte
- src/lib/nativeHooks/TEEPlugin.ts
- src/lib/preferences/prefereces.ts
- src/routes/+error.svelte
- src/routes/login/+page.ts
- src/routes/r/native/+page.svelte
- src/routes/r/profile/+page.svelte
- feat: TEE encrypt/decrypt using AES/GCM
- feat: keyring is encrypted in local storage
- feat: createKey native function
- feat: TEEPlugin handle encrypt and decrypt also in IOS
> feat: TEE for android and ios

- package.json
- pnpm-lock.yaml
- src/lib/forms/textInput.svelte
- src/lib/keypairoom/Seeds.svelte
- src/lib/slangroom/contracts.ts
- src/lib/slangroom/endpoints.ts
- src/lib/slangroom/index.ts
- src/routes/r/+layout.svelte
- src/routes/r/slangroom/+page.svelte
- build: update zenroom version, add slangroom
- feat: test some slangroom resquests
- refactor: slangroom lib
- feat: login with slangroom
- fix: handle some error
> feat: didroom api

- fastlane/Fastfile
> ci: touch .env for properly build app

- .github/workflows/build_alpha_release.yml
- fastlane/Fastfile
- fix: env to be fed to svelte build
- fix: use better solution (github envoiroments variables
- fix: use .env.example in ci
- fix: use .env.example in ci
> fix: sveltekit env path 

- android/app/capacitor.build.gradle
- android/capacitor.settings.gradle
- ios/App/Podfile
- messages/en.json
- messages/it.json
- package.json
- pnpm-lock.yaml
- src/lib/components/languageSwitcher.svelte
- src/lib/i18n/index.ts
- src/lib/preferences/lang.ts
- src/lib/tabs/TabPage.svelte
- src/routes/+page.ts
- src/routes/[[lang]]/(auth)/unlock/+page.svelte
- src/routes/[[lang]]/(protected)/+layout.ts
- src/routes/[[lang]]/(protected)/home/+page.svelte
> Feat: use device locale

- package.json
Also added the @slangroom/zencode package
> slangroom and zenroom to latest

- src/lib/preferences/did.ts
- src/lib/preferences/signroomUser.ts
- src/routes/[[lang]]/(auth)/login/(methods)/questions/+page.svelte
- src/routes/[[lang]]/(auth)/login/_lib/index.ts
- fix: did generation on android and ios
- fix: TEE error on android after login
> fix devices did

- pnpm-lock.yaml
- src/lib/components/organisms/scanner/tools.ts
- src/lib/i18n/index.ts
- src/lib/openId4vci/contracts.ts
- src/lib/openId4vci/index.ts
- src/lib/preferences/credentials.ts
- src/lib/slangroom/index.ts
- src/routes/[[lang]]/(protected)/[id]/credential-detail/+page.svelte
- src/routes/[[lang]]/(protected)/[id]/credential-offer/+page.svelte
- src/routes/[[lang]]/(protected)/scan/+page.svelte
- fix: update zenroom to latest
- feat: initial implementation of holder_to_authorize_on_authz_server
> feat: openId4VCI

- src/hooks.client.ts
- src/lib/forms/form.svelte
- src/lib/log.ts
- src/lib/preferences/index.ts
- src/lib/preferences/logs.ts
- src/lib/preferences/user.ts
- src/routes/+error.svelte
- src/routes/+layout.svelte
- src/routes/logs/+page.svelte
- src/routes/logs/+page.ts
- **chore: catch global errors**
- **fix: handlee nt logs yet registered**
- **fix: login issues in android**
> fix: login completation on android

- package.json
- pnpm-lock.yaml
- src/lib/components/organisms/scanner/Scanner.svelte
- src/lib/components/organisms/scanner/tools.ts
- src/lib/preferences/credentials.ts
- src/routes/[[lang]]/(protected)/scan/+page.svelte
- **draft: verification flow initial implementation**
- **feat: show asked claims on verifications**
> feat: verification flow

- src/lib/tabs/IonTabs.svelte
- src/routes/[[lang]]/(protected)/credential-offer/+page.svelte
- **fix: remove vertical padding to tab bar**
- **fix: hided buttons in some credential offers**
fix: #285
> fix: tab bar was too height

- src/routes/[[lang]]/(protected)/verification/+page.svelte
> fix: the verify button should be pressable only one time

- src/lib/components/organisms/scanner/Scanner.svelte
> fix: in scanner mode after request permission start to scan

- src/lib/components/molecules/Header.svelte
- src/lib/components/molecules/Settings.svelte
- src/routes/+layout.svelte
- src/routes/[[lang]]/(protected)/languages/+page.svelte
- src/routes/[[lang]]/(protected)/profile/+page.svelte
needs https://github.com/ForkbombEu/didroom-components/pull/85 then update src/routes/+layout.svelte
> feat: app settings

- src/lib/credentialOfferStore.ts
- src/routes/[[lang]]/(protected)/credential-offer/+page.svelte
- src/routes/[[lang]]/(protected)/home/+page.svelte
- src/routes/[[lang]]/(protected)/scan/+page.svelte
> fix: when decline a credential offer sometimes the app lands on a white page

- src/lib/ionic/forms/input.svelte
- src/routes/+layout.svelte
- src/routes/[[lang]]/(auth)/login/(methods)/insert-password/+page.svelte
- src/routes/[[lang]]/(auth)/login/+page.svelte
> fix: make password inputs showable

- src/routes/[[lang]]/(auth)/login/(methods)/passphrase/+page.svelte
> fix: passhprase view

- src/routes/[[lang]]/(auth)/login/(methods)/questions/+page.svelte
> fix: remove back button after keypairs are generated

- src/lib/components/organisms/scanner/Scanner.svelte
> fix: on hardware back button close the qr scanner

- messages/en.json
- src/routes/[[lang]]/(auth)/login/+page.svelte
> fix: feedbacks on login attempt

- src/routes/[[lang]]/(protected)/credential-offer/+page.svelte
> fix: remove the dialog/modal when in /credential-offer something goes wrong

- src/routes/[[lang]]/(protected)/home/+page.svelte
> fix: in /home the description of services are missing

- src/lib/components/molecules/Settings.svelte
- src/lib/openId4vci/index.ts
- src/routes/[[lang]]/(protected)/wallet/+page.svelte
- tests/activity.spec.ts
- tests/credential-detail.spec.ts
- tests/credential-offer.spec.ts
- tests/home.spec.ts
- tests/login.spec.ts
- tests/onboarding.spec.ts
- tests/profile.spec.ts
- tests/register.spec.ts
- tests/settings.spec.ts
- tests/utils/index.ts
- tests/verify.spec.ts
- tests/wallet.spec.ts
- **tests: /profile**
- **test: /wallet**
- **tests: /activity**
- **test: credential-detail**
- **refactor: split some test for performance**
> test: add more e2e tests

- src/routes/[[lang]]/(auth)/login/(methods)/questions/+page.svelte
- src/routes/[[lang]]/(auth)/login/_lib/index.ts
> fix: at login if user has not yet remote keypar save it

- src/routes/+layout.svelte
- src/routes/[[lang]]/(protected)/[id]/credential-detail/+page.svelte
- src/routes/[[lang]]/(protected)/wallet/+page.svelte
- tests/activity.spec.ts
- tests/credential-detail.spec.ts
> fix: show disclosures in credential details

- src/routes/[[lang]]/(protected)/credential-offer/+page.svelte
> fix: remove get credential button in credential offer

- src/lib/tabs/IonTabs.svelte
> fix: app freezed in loading state

- messages/en.json
- playwright.config.ts
- src/lib/preferences/credentials.ts
- src/routes/+layout.svelte
- src/routes/[[lang]]/(protected)/[id]/credential-detail/+page.svelte
- src/routes/[[lang]]/(protected)/credential-offer/+page.svelte
- src/routes/[[lang]]/(protected)/home/+page.svelte
- src/routes/[[lang]]/(protected)/profile/+page.svelte
- src/routes/[[lang]]/(protected)/wallet/+page.svelte
needs: didroom-components 1.26.2
> chores: update didroom-components

- src/lib/components/molecules/Modal.svelte
- src/lib/components/organisms/scanner/tools.ts
- src/routes/[[lang]]/(protected)/scan/+page.svelte
> fix: close button and hardware back doesnt work on scan error modal

- src/lib/forms/form.svelte
- src/lib/forms/input.svelte
- src/routes/[[lang]]/(auth)/login/(methods)/insert-password/+page.svelte
- src/routes/[[lang]]/(auth)/login/(methods)/passphrase/+page.svelte
- src/routes/[[lang]]/(auth)/login/+page.svelte
- src/routes/[[lang]]/(auth)/login/reset-password/+page.svelte
> fix: disable submit buttons when forms are not tainted

- messages/en.json
- src/routes/[[lang]]/(protected)/credential-offer/+page.svelte
- src/routes/[[lang]]/(protected)/scan/+page.svelte
> fix: human readeable errors on scan failure (missing credential, qr code is expired)

- src/lib/forms/checkbox.svelte
- src/routes/+layout.svelte
- src/routes/[[lang]]/(auth)/login/+page.svelte
- tests/register.spec.ts
close: #436 
~~needs: https://github.com/ForkbombEu/didroom-components/pull/146~~
> feat: terms and conditions at registration time

- .github/workflows/build_alpha_release.yml
> chore: bump fastlane action in aplha workflow

- src/lib/components/molecules/HeaderWithBackButton.svelte
- src/routes/+layout.svelte
- src/routes/[[lang]]/(auth)/login/(methods)/insert-password/+page.svelte
- src/routes/[[lang]]/(protected)/languages/+page.svelte
- src/routes/[[lang]]/(protected)/profile/+page.svelte
fix: https://github.com/ForkbombEu/wallet/issues/455
> fix: back button in header and settings menu

- src/lib/homeFeedbackPreferences.ts
- src/lib/preferences/activity.ts
- src/lib/tabs/IonTabs.svelte
- src/routes/+layout.svelte
- src/routes/[[lang]]/(protected)/+layout.svelte
- src/routes/[[lang]]/(protected)/+layout.ts
- src/routes/[[lang]]/(protected)/activity/+page.svelte
- src/routes/[[lang]]/(protected)/home/+page.svelte
> fix: tab bar

- .github/workflows/alpha_version.yml
- .github/workflows/firebase_version.yml
- src/lib/components/organisms/scanner/tools.ts
- src/lib/preferences/activity.ts
close: #485
may need: https://github.com/ForkbombEu/mobile_zencode/issues/57
> fix: verifier logo in activities card

- .github/workflows/alpha_version.yml
- .github/workflows/beta_version.yml
- .github/workflows/build-upload-ios.yml
- .github/workflows/firebase_version.yml
- .github/workflows/github_version.yml
- .github/workflows/publish_on_production.yml
- .github/workflows/translations.yml
- .tool-versions
- fastlane/Fastfile
- pnpm-lock.yaml
refactor:
1. When a pull request is opened, two workflows are triggered: **🍏✨ Flight of the iPhoenix** (iOS TestFlight) and **🔥📲 Droid FireDrop** (Fireship app distribution).  
2. When merging to the `main` branch: **🐙📦 OctoShip Delivery** (GitHub release) and **🤖🌈 Droid Alpha Skunkworks** (Play Store closed testing).  
3. When merging to the `stable` branch: **🤖🎯 Droid Beta Launchpad** (Play Store open testing).  
4. On request, but only from the `stable` branch and selecting between iOS, Android, or both: **🚀🌍 Universal Stardust Release**.
> feat: publish production version on play store

- src/routes/[[lang]]/(auth)/login/+page.svelte
- tests/activity.spec.ts
> fix: add back button on login or register

- .github/workflows/alpha_version.yml
- .github/workflows/beta_version.yml
- .github/workflows/build-upload-ios.yml
- .github/workflows/firebase_version.yml
- .github/workflows/publish_on_production.yml
- .github/workflows/ship_android.yml
- .github/workflows/ship_ios.yml
- fastlane/Fastfile
- **fix: provide unreleased changhes when submitting to ios**
- **refactor: build and ship ios app job**
> fix: provide unreleased changhes when submitting to ios 

- package.json
- pnpm-lock.yaml
- src/routes/[[lang]]/(auth)/login/+page.svelte
needs: https://github.com/ForkbombEu/didroom-components/pull/195
> fix: checkbox accessibility

- src/lib/verificationResultsStore.ts
- src/routes/[[lang]]/(protected)/verification/results/+page.svelte
- src/routes/[[lang]]/(protected)/verification/select-credential/+page.svelte
- fix: verification results
- fix: if not id setted verification results should be visible anyway
> fix: verification results

- .tool-versions
- **fix: bump mobile_zencode to latest**
- **chore(mise): fix version of java and add also gradle**
> fix: bump mobile_zencode to latest
